### ISSUE TITLE
Question: how to create sub-hourly snapshots

### ISSUE THREAD

**Issue by rmallah** [jimsalterjrs/sanoid#228] opened 2018-06-07 02:25 UTC
Hi , 

I need to keep snapshots of every 15th minute of a given day.
eg we want to have 24 * 4 = 96 snapshots per day .

**Comment by redmop** [comment] 2018-06-07 02:29
Sanoid currently doesn't support that. It supports these periods: yearly, monthly, daily, hourly

**Comment by rmallah** [comment] 2018-06-07 02:54
Thanks for the quick response. 
just curious is the omission intentional or is it in the roadmap?
regds
mallah.

**Comment by redmop** [comment] 2018-06-07 04:10
I'm not sure. (I'm not the dev, I just knew the answer.)

**Comment by phreaker0** [comment] 2018-06-07 06:20
@rmallah 
you can use my PR branch #157 which implements the frequently snapshots you need. I'm running it for 15 minutes snapshots on several machines.

**Comment by rmallah** [comment] 2018-06-07 06:28
@phreaker0 thanks for that. Wondering why the pr does not becomes a feature in the main repo.

**Comment by phreaker0** [comment] 2018-06-07 09:36
@jimsalterjrs wants to review and test it properly before merging, if it works for you or if there a problems you could express that in the PR.

**Comment by phreaker0** [comment] 2018-09-04 21:14
duplicate of #75

**Closed by phreaker0** 2018-09-04 21:14 UTC
