### ISSUE TITLE
Recursive is not atomic on child datasets compared to parent

### ISSUE THREAD

**Issue by tomposmiko** [jimsalterjrs/sanoid#244] opened 2018-07-24 10:38 UTC
If `syncoid -r` is in use, the parent and child datasets are not snapshotted at the same time.
Snapshots are created with `foreach` and not with `zfs snap -r`.

**Comment by phreaker0** [comment] 2018-07-26 20:05
"zfs snapshot -r" doesn't allow to exclude some child datasets, but sanoid supports that use case. Maybe some logic an be implemented to detect if an entire subtree should be snapshots with no ignores and in that case use atomic snapshots.

Another option I was thinking about is to group all datasets and take all snapshots in one call to zfs snapshot. But i can't find any information if this will be done atomically in that way.

**Comment by jimsalterjrs** [comment] 2018-07-26 20:14
`zfs snapshot -r` is atomic. But, as you said, it doesn't support exclusions.

There's been talk of using `zfs snapshot -r` in sanoid - and for that matter, `zfs send -r` in syncoid - but so far I haven't been willing to either discard the more granular methodology both are capable of, or implement some kind of logic to detect when ZFS native recursion can or can't be used.

I also strongly suspect it would create more corner cases that would confuse many users TBH.

**Comment by phreaker0** [comment] 2018-07-26 20:22
I misread and was thinking solely of sanoid, not syncoid, but yeah it affects both.
@jimsalterjrs 
do you know if "zfs snapshot pool/ds1@test pool/ds2@test pool/ds3@test" is atomic?

**Comment by phreaker0** [comment] 2018-07-26 20:42
I interpret the zfs manpage here: https://www.freebsd.org/cgi/man.cgi?zfs(8) that all datasets given to the snapshot command are atomically created. 

So this may be a way to implement atomic snapshots, but I guess this would be quite some work.

**Comment by phreaker0** [comment] 2018-09-04 20:56
duplicate of #104

**Closed by phreaker0** 2018-09-04 20:56 UTC
