### ISSUE TITLE
Add -n/--dry-run option

### ISSUE THREAD

**Issue by wyoung** [jimsalterjrs/sanoid#221] opened 2018-05-03 00:24 UTC
While debugging the issues related to #219, I'd have liked the option to have it just print on screen what it planned to do, so I wouldn't have to go into the sub-filesystems of those I don't want being treated recursively and destroy the unwanted snapshots.

Standard practice is to implement this as `-n` and (optionally) as `--dry-run`.

**Comment by sparky3387** [comment] 2018-06-16 01:53
FYI the verbose and readonly options combined  create this

**Comment by serg-ku** [comment] 2018-12-28 15:19
This will be very useful in sycoid.

**Comment by Follpvosten** [comment] 2020-06-08 07:56
I'd very much like such an option for syncoid, especially to test if my regexes for `--exclude` have the intended effect.

**Comment by dlangille** [comment] 2020-07-25 14:42
Duplicate of #11

**Comment by phreaker0** [comment] 2020-07-28 19:41
@dlangille this is about sanoid, not syncoid. With the --readonly option this should already be solved @wyoung right?

**Closed by phreaker0** 2020-07-28 19:41 UTC
Labels: enhancement
