### ISSUE TITLE
syncoid: “~ UNKNOWN” size after updating a target to FreeBSD 11.3-RELEASE

### ISSUE THREAD

**Issue by ejpcmac** [jimsalterjrs/sanoid#449] opened 2019-11-05 10:59 UTC
## Issue description

I use to backup a FreeBSD server by *pulling* its ZFS datasets on a Linux NAS using syncoid (syncoid runs on the Linux side). Until upgrading my FreeBSD server from FreeBSD 11.2-RELEASE to FreeBSD 11.3-RELEASE, all worked properly. Now, I get `~ UNKNOWN` instead of the actual size during the transfers. No other errors are reported.

Using syncoid between Linux hosts (local, push, pull) work properly.

Maybe I’m missing something on the FreeBSD side? Both `mbuffer` and `lzop` are installed there.

## Versions

* syncoid: 2.0.2 (packaged [here](https://github.com/ejpcmac/nixpkgs-jpc/blob/master/pkgs/syncoid/default.nix))
* Linux distro: NixOS 19.09
* FreeBSD : 11.3-RELEASE (but syncoid is not run nor installed here)

**Comment by phreaker0** [comment] 2019-11-05 12:03
duplicate of #414, fix is already proposed here #415

**Closed by phreaker0** 2019-11-05 12:03 UTC

**Comment by ejpcmac** [comment] 2019-11-05 12:09
@phreaker0 I did not look for the correct keywords then. I’ll try your patch, thank you!
