### ISSUE TITLE
syncoid not processing clones properly

### ISSUE THREAD

**Issue by valeech** [jimsalterjrs/sanoid#138] opened 2017-08-21 15:27 UTC
On initial sync, the destination receives full data for clones and the origin is broken.

So if you have clones chained off of each other, all clones on the destination will be full size and not linked!

SOURCE POOL:
https://pastebin.com/7dqX0qks

After running ./syncoid -r testpool root@desthost:testpool/testclient

DESTINATION POOL:
https://pastebin.com/yHtrpy69

**Comment by phreaker0** [comment] 2018-09-04 20:12
duplicate of #49

**Closed by phreaker0** 2018-09-04 20:12 UTC
