### ISSUE TITLE
Sanoid 2.0.2-2 service not starting on 01.10.2019

### ISSUE THREAD

**Issue by peter-held** [jimsalterjrs/sanoid#439] opened 2019-10-01 05:52 UTC
Oct 01 08:49:36 srv1 systemd[1]: Starting Sanoid...
Oct 01 08:49:36 srv1 sanoid[162757]: Day '0' out of range 1..31 at /usr/bin/sanoid line 413.
Oct 01 08:49:36 srv1 sanoid[162757]: INFO: taking snapshots...
Oct 01 08:49:36 srv1 systemd[1]: sanoid.service: Main process exited, code=exited, status=255/EXCEPTION
Oct 01 08:49:36 srv1 systemd[1]: sanoid.service: Failed with result 'exit-code'.
Oct 01 08:49:36 srv1 systemd[1]: Failed to start Sanoid.

**Comment by thoomasb** [comment] 2019-10-01 06:31
Similar issue here. Starting sanoid by cron:

`*/5 * * * * root TZ=UTC /usr/bin/sanoid --cron`

Getting the same error message as mentioned in the initial post:

`Day '0' out of range 1..31 at /usr/bin/sanoid line 413.`

Installed sanoid using the sanoid-2.0.2.tar.gz download from the github repo.

Seems caused by Time::Local and the `$preferredtime[3] -= 1` statement on line 412.

**Comment by thoomasb** [comment] 2019-10-01 06:39
Forgot to mention: no snapshots are created now, so it seems like the code is not completely fail-safe.

**Comment by phreaker0** [comment] 2019-10-01 07:06
This bug is fixed in latest master (#394).

**Comment by redmop** [comment] 2019-10-01 13:29
It should start working tomorrow.

**Comment by kfkawalec** [comment] 2019-11-01 06:02
There will by any fix for this? Today is the same situation :(

**Comment by phreaker0** [comment] 2019-11-01 10:13
@kfkawalec new release is prepared as PR here (#441)
@jimsalterjrs many people are affected by the issue here, I think the bugfix release should be made soon.

**Closed** 2019-11-02 02:05 UTC

**Comment by jimsalterjrs** [comment] 2019-11-02 02:11
fixes merged; v2.0.3 release created.
