### ISSUE TITLE
feature request for syncoid: ability to resume send/receive if native zfs command supports it

### ISSUE THREAD

**Issue by mailinglists35** [jimsalterjrs/sanoid#68] opened 2017-01-25 14:48 UTC
it would be very useful to detect support of "-s" flag on "zfs receive" command (and corresponding "-t" on "zfs send") and take advantage of it to resume interrupted sends - like when you have a very large snapshot and network interrupts and you have to start again sending the large snapshot

**Comment by arronmabrey** [comment] 2017-04-10 17:19
I'm also interested in this setup. I'm using openzfs for macOS, which supports send/receive resume.

**Comment by jimsalterjrs** [comment] 2017-07-12 20:04
Closing as (effective) dupe of #88 . I'm blocking on this until bookmarks / resumable send and receive make it into mainstream ZoL (to wit, Ubuntu 16.04 Ubuntu repos).

I *am* willing to accept PRs that depend on code in OpenZFS master, so long as they gracefully handle the lack of bookmark / resume features in older ZFS versions.

**Closed by jimsalterjrs** 2017-07-12 20:04 UTC

**Comment by mailinglists35** [comment] 2018-01-26 08:12
>  I'm blocking on this until bookmarks / resumable send and receive make it into mainstream ZoL (to wit, Ubuntu 16.04 Ubuntu repos)

centos already has packages for 0.7 release which includes bookmarks. why wait until ubuntu, and even unsure if ubuntu will have 0.7?
https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1734172?comments=all
