### ISSUE TITLE
propagate snapshot removal

### ISSUE THREAD

**Issue by mat813** [jimsalterjrs/sanoid#488] opened 2020-01-28 12:17 UTC
I have local automatic snapshots created by some other tool named zfstools, so this lives on by itself just fine, and I am using syncoid to backup my whole pool to a remote server with this command:

```
syncoid --recursive --sendoptions="Lc e" --recvoptions="u" zroot  root@backupbox:zroot/backup/local-hostname
```

This works great and is much faster than the rsync I was running before.

Now, snapshots gets expired locally regularly, say, I have "frequent" category of snapshots done every 15 minutes, and I keep 36 of them, then I have hourly snapshots, that I keep 70 of, etc... locally, they get removed regularly, but on the backup server, over the time, they accumulate, it seems syncoid does nothing to remove snapshots that are no longer there.

**Comment by gdevenyi** [comment] 2020-01-28 13:48
Duplicate of https://github.com/jimsalterjrs/sanoid/issues/477

**Closed** 2020-01-28 14:21 UTC
