### ISSUE TITLE
syncoid was broke with probable typo for zfs list

### ISSUE THREAD

**Issue by croadfeldt** [jimsalterjrs/sanoid#480] opened 2020-01-18 07:51 UTC
Copy -n- paste of my comment below. 

> This broke zfs list with and invalid argument of "A-Hpd" I believe it should be "-Hpd". There no "A" parameter for zfs list.

Removing the errant A from the command line arguments returns syncoid back to the land of functionality.

Eh, made a PR for it... :)

Link to comment and broke commit / code: https://github.com/jimsalterjrs/sanoid/commit/28ef311ba5b337a9e0283088825cd92f0dfbe01b#r36857988

**Comment by phreaker0** [comment] 2020-01-18 11:46
@croadfeldt but syncoid still worked right? Because it should then have used the fallback code for getting snapshots.

**Comment by croadfeldt** [comment] 2020-01-18 16:21
No, the process stopped stating it could not get a list of the available snapshots.

**Comment by phreaker0** [comment] 2020-01-19 11:22
@croadfeldt which OS, zfs version and can you provide me with a "--debug" output. The fallback code ideally should work everywhere.

**Comment by mac-linux-free** [comment] 2020-01-19 20:19
for me too...os is debian 10

**Comment by phreaker0** [comment] 2020-01-19 20:45
@mac-linux-free can you run "zfs get -Hpd 1 type,guid,creation <dataset>" and post some of the output, this is the command for the fallback solution which should work on linux.

**Comment by mac-linux-free** [comment] 2020-01-19 20:54
nvme	type	filesystem	-
nvme	guid	7512108755123831829	-
nvme	creation	1550740754	-
nvme/test	type	filesystem	-
nvme/test	guid	14113749373428844446	-
nvme/test	creation	1579293384	-
nvme/vms	type	filesystem	-
nvme/vms	guid	14162807739117640480	-
nvme/vms	creation	1550740823	-
quadtb	type	filesystem	-
quadtb	guid	2783484955227258090	-
quadtb	creation	1550741796	-
quadtb/iso	type	filesystem	-
quadtb/iso	guid	2165255909327928274	-
quadtb/iso	creation	1579459096	-
quadtb/lxc	type	filesystem	-
quadtb/lxc	guid	12296211639018301465	-
quadtb/lxc	creation	1550741877	-
quadtb/vms	type	filesystem	-
quadtb/vms	guid	5699146028676988360	-
quadtb/vms	creation	1550741835	-
quadtb/vzdump	type	filesystem	-
quadtb/vzdump	guid	11326001782360719824	-
quadtb/vzdump	creation	1550750648	-
rpool	type	filesystem	-
rpool	guid	13258490823988030052	-
rpool	creation	1550007457	-
rpool/ROOT	type	filesystem	-
rpool/ROOT	guid	17750911840999820409	-
rpool/ROOT	creation	1550007457	-
rpool/data	type	filesystem	-
rpool/data	guid	637101981945328961	-
rpool/data	creation	1550007457	-
rpool/swap	type	volume	-
rpool/swap	guid	13565399337238186378	-
rpool/swap	creation	1562835511	-

**Comment by mac-linux-free** [comment] 2020-01-19 20:54
nvme	type	filesystem	-
nvme	guid	7512108755123831829	-
nvme	creation	1550740754	-
nvme/test	type	filesystem	-
nvme/test	guid	14113749373428844446	-
nvme/test	creation	1579293384	-
nvme/vms	type	filesystem	-
nvme/vms	guid	14162807739117640480	-
nvme/vms	creation	1550740823	-
quadtb	type	filesystem	-
quadtb	guid	2783484955227258090	-
quadtb	creation	1550741796	-
quadtb/iso	type	filesystem	-
quadtb/iso	guid	2165255909327928274	-
quadtb/iso	creation	1579459096	-
quadtb/lxc	type	filesystem	-
quadtb/lxc	guid	12296211639018301465	-
quadtb/lxc	creation	1550741877	-
quadtb/vms	type	filesystem	-
quadtb/vms	guid	5699146028676988360	-
quadtb/vms	creation	1550741835	-
quadtb/vzdump	type	filesystem	-
quadtb/vzdump	guid	11326001782360719824	-
quadtb/vzdump	creation	1550750648	-
rpool	type	filesystem	-
rpool	guid	13258490823988030052	-
rpool	creation	1550007457	-
rpool/ROOT	type	filesystem	-
rpool/ROOT	guid	17750911840999820409	-
rpool/ROOT	creation	1550007457	-
rpool/data	type	filesystem	-
rpool/data	guid	637101981945328961	-
rpool/data	creation	1550007457	-
rpool/swap	type	volume	-
rpool/swap	guid	13565399337238186378	-
rpool/swap	creation	1562835511	-

**Comment by phreaker0** [comment] 2020-01-19 20:57
@mac-linux-free thx, the output form looks like expected. Just to be sure, there are lines with "... type snapshot" somewhere right?
If so could you provide me with a "syncoid --debug" run with the typo still in place and post the output?

**Comment by rwarren** [comment] 2020-01-24 04:42
This is still broken, Why not just drop the `A`?

I can confirm taht fallback code doesn't work for me, either.  `zfs get -Hpd 1 type,guid,creation data/images` works perfectly fine for me at both source and destination, though.

**Comment by phreaker0** [comment] 2020-01-24 10:12
@rwarren there is already a PR for it waiting to be merged #481 :-) . I justl want to know why the fallback code doesn't work for some people here. Maybe you can provide me with:

- 'zfs get -Hpd 1 type,guid,creation' of src dataset
- 'zfs get -Hpd 1 type,guid,creation' of dst dataset
- syncoid --debug src dst output

Please also post zfs version and os.

**Closed** 2020-01-24 13:46 UTC
