### ISSUE TITLE
Syncoid with `—quiet` option lists all datasets (likely related to `—exclude` option)

### ISSUE THREAD

**Issue by albertmichaelj** [jimsalterjrs/sanoid#326] opened 2019-01-13 19:19 UTC
I am using the below syncoid command to replicate my root dataset (rpool) to an array of local hard disks:

```
/usr/local/bin/syncoid -r --quiet --exclude=rpool/docker --exclude=rpool/lxd --exclude=rpool/var/tmp --exclude=rpool/swap --exclude=rpool/var/cache --exclude=rpool/home/michael/Temp rpool array/Root_Backup
```

Since I’m using the `—quiet` option, I expected there to be no output unless there is an error. However, I’m getting a list of all of the datasets under rpool (this is a partial list...):
```
rpool/srv
rpool/srv
rpool/srv
rpool/srv
rpool/swap
rpool/swap
rpool/swap
rpool/swap
rpool/var
rpool/var
rpool/var
rpool/var
rpool/var
rpool/var
rpool/var/cache
rpool/var/cache
rpool/var/cache
rpool/var/cache
rpool/var/cache
rpool/var/games
rpool/var/games
rpool/var/games
rpool/var/games
rpool/var/games
rpool/var/games
rpool/var/log
rpool/var/log
rpool/var/log
rpool/var/log
rpool/var/log
rpool/var/log
rpool/var/mail
rpool/var/mail
rpool/var/mail
rpool/var/mail
rpool/var/mail
rpool/var/mail
rpool/var/nfs
rpool/var/nfs
rpool/var/nfs
rpool/var/nfs
rpool/var/nfs
rpool/var/nfs
rpool/var/spool
rpool/var/spool
rpool/var/spool
rpool/var/spool
rpool/var/spool
rpool/var/spool
rpool/var/tmp
rpool/var/tmp
rpool/var/tmp
```

It’s basically listing all of my datasets under rpool six times (except for datasets I exclude), and I use the exclude command six times. So, I suspect somewhere in the `—exclude` code there is a line printing out all of the datasets. This means that the `—quiet` command is not sufficient for avoiding annoying emails from cron, and I have to redirect standard output instead.

Let me know if I can help debug anymore!

**Comment by phreaker0** [comment] 2019-01-13 20:20
Duplicate of #314 and fix is prepared here #319.

**Closed by phreaker0** 2019-01-13 20:20 UTC
