### ISSUE TITLE
bug: the bookmark fallback code does not get executed when --no-sync-snap is provided and there is at least one matching bookmark/snapshot pair AND the source has just one snapshot

### ISSUE THREAD

**Issue by mailinglists35** [jimsalterjrs/sanoid#338] opened 2019-01-29 23:23 UTC
Using latest git master

In `syncdataset()`, `$newsyncsnap` is evaluated from `getnewestsnapshot()` **before** checking for source bookmarks matching destination snapshots.

If the source has no matching snapshots, but still have valid matching guids, `syncdataset()` calls `getnewestsnapshot()` which dies because `getnewestsnapshot()` only compares snapshots, not guids of bookmarks and snapshots

To reproduce:

create source/fs1, target
replicate initially with default options
create bookmark of source snapshot
delete source snapshot
(optionally) manually create a snapshot 
attempt to synchronize with --no-sync-snap

results are different, first without manually created snapshot (scroll for the second case. I think these are actually two issues but I'm pasting both here)

````
[suport@zfspv ~]$ syncoid --debug --no-sync-snap --sendoptions="-Lc" --recvoptions="-vu"  suport@zfshq:bkphq/delete bkppv/encrypted/bkphq/delete
DEBUG: SSHCMD: /usr/bin/ssh
DEBUG: checking availability of /usr/bin/lzop on source...
DEBUG: checking availability of /usr/bin/lzop on target...
DEBUG: checking availability of /usr/bin/lzop on local machine...
DEBUG: checking availability of /usr/bin/mbuffer on source...
DEBUG: checking availability of /usr/bin/mbuffer on target...
DEBUG: checking availability of /usr/bin/pv on local machine...
DEBUG: checking availability of zfs resume feature on source...
DEBUG: checking availability of zfs resume feature on target...
DEBUG: syncing source bkphq/delete to target bkppv/encrypted/bkphq/delete.
DEBUG: getting current value of syncoid:sync on bkphq/delete...
/usr/bin/ssh     -S /tmp/syncoid-suport-suport@zfshq-1548801456 suport@zfshq /usr/bin/sudo /sbin/zfs get -H syncoid:sync ''"'"'bkphq/delete'"'"''
DEBUG: checking to see if bkppv/encrypted/bkphq/delete on  is already in zfs receive using  /bin/ps -Ao args= ...
DEBUG: checking to see if target filesystem exists using " /usr/bin/sudo /sbin/zfs get -H name 'bkppv/encrypted/bkphq/delete' 2>&1 |"...
DEBUG: getting current value of receive_resume_token on bkppv/encrypted/bkphq/delete...
 /usr/bin/sudo /sbin/zfs get -H receive_resume_token 'bkppv/encrypted/bkphq/delete'
DEBUG: no receive token found
DEBUG: getting list of snapshots on bkphq/delete using /usr/bin/ssh     -S /tmp/syncoid-suport-suport@zfshq-1548801456 suport@zfshq /usr/bin/sudo /sbin/zfs get -Hpd 1 -t snapshot guid,creation ''"'"'bkphq/delete'"'"'' |...
DEBUG: getting list of snapshots on bkppv/encrypted/bkphq/delete using  /usr/bin/sudo /sbin/zfs get -Hpd 1 -t snapshot guid,creation 'bkppv/encrypted/bkphq/delete' |...
CRIT: --no-sync-snap is set, and getnewestsnapshot() could not find any snapshots on source!
````

with manually created snapshot it behaves a bit different: it finds the bookmark and completes the send from bookmark but then it attempts to send again the same snapshot and it fails
````
[suport@zfspv ~]$ LANG="en_US.utf-8" /tmp/syncoid.fix-bookmark --debug --no-sync-snap --sendoptions="-Lc" --recvoptions="-vu"  suport@zfshq:bkphq/delete bkppv/encrypted/bkphq/delete
DEBUG: SSHCMD: /usr/bin/ssh
DEBUG: checking availability of /usr/bin/lzop on source...
DEBUG: checking availability of /usr/bin/lzop on target...
DEBUG: checking availability of /usr/bin/lzop on local machine...
DEBUG: checking availability of /usr/bin/mbuffer on source...
DEBUG: checking availability of /usr/bin/mbuffer on target...
DEBUG: checking availability of /usr/bin/pv on local machine...
DEBUG: checking availability of zfs resume feature on source...
DEBUG: checking availability of zfs resume feature on target...
DEBUG: syncing source bkphq/delete to target bkppv/encrypted/bkphq/delete.
DEBUG: getting current value of syncoid:sync on bkphq/delete...
/usr/bin/ssh     -S /tmp/syncoid-suport-suport@zfshq-1548803638 suport@zfshq /usr/bin/sudo /sbin/zfs get -H syncoid:sync ''"'"'bkphq/delete'"'"''
DEBUG: checking to see if bkppv/encrypted/bkphq/delete on  is already in zfs receive using  /bin/ps -Ao args= ...
DEBUG: checking to see if target filesystem exists using " /usr/bin/sudo /sbin/zfs get -H name 'bkppv/encrypted/bkphq/delete' 2>&1 |"...
DEBUG: getting current value of receive_resume_token on bkppv/encrypted/bkphq/delete...
 /usr/bin/sudo /sbin/zfs get -H receive_resume_token 'bkppv/encrypted/bkphq/delete'
DEBUG: no receive token found
DEBUG: getting list of snapshots on bkphq/delete using /usr/bin/ssh     -S /tmp/syncoid-suport-suport@zfshq-1548803638 suport@zfshq /usr/bin/sudo /sbin/zfs get -Hpd 1 -t snapshot guid,creation ''"'"'bkphq/delete'"'"'' |...
DEBUG: getting list of snapshots on bkppv/encrypted/bkphq/delete using  /usr/bin/sudo /sbin/zfs get -Hpd 1 -t snapshot guid,creation 'bkppv/encrypted/bkphq/delete' |...
NEWEST SNAPSHOT: snap1manual
DEBUG: getting current value of -p used on bkppv/encrypted/bkphq/delete...
 /usr/bin/sudo /sbin/zfs get -H -p used 'bkppv/encrypted/bkphq/delete'
DEBUG: getting list of bookmarks on bkphq/delete using /usr/bin/ssh     -S /tmp/syncoid-suport-suport@zfshq-1548803638 suport@zfshq /usr/bin/sudo /sbin/zfs get -Hpd 1 -t bookmark guid,creation ''"'"'bkphq/delete'"'"'' 2>&1 |...
DEBUG: checking to see if bkppv/encrypted/bkphq/delete on  is already in zfs receive using  /bin/ps -Ao args= ...
DEBUG: rolling back target to bkppv/encrypted/bkphq/delete@syncoid_zfspv.silor_2019-01-30:01:11:12...
/usr/bin/sudo /sbin/zfs rollback -R 'bkppv/encrypted/bkphq/delete'@'syncoid_zfspv.silor_2019-01-30:01:11:12'
Sending incremental bkphq/delete#'syncoid_zfspv.silor_2019-01-30:01:11:12' ... snap1manual (~ UNKNOWN):
DEBUG: /usr/bin/ssh     -S /tmp/syncoid-suport-suport@zfshq-1548803638 suport@zfshq '/usr/bin/sudo /sbin/zfs send -Lc -i '"'"'bkphq/delete'"'"'#'"'"'syncoid_zfspv.silor_2019-01-30:01:11:12'"'"' '"'"'bkphq/delete'"'"'@'"'"'snap1manual'"'"' | /usr/bin/lzop  | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null' | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc | /usr/bin/pv -s 0 | /usr/bin/sudo /sbin/zfs receive -vu -s -F 'bkppv/encrypted/bkphq/delete'
 624 B 0:00:00 [11.5kiB/s] [   <=>                                                                                                                                                                              ]
receiving incremental stream of bkphq/delete@snap1manual into bkppv/encrypted/bkphq/delete@snap1manual
received 312B stream in 1 seconds (312B/sec)
DEBUG: getting estimated transfer size from source -S /tmp/syncoid-suport-suport@zfshq-1548803638 suport@zfshq using "/usr/bin/ssh     -S /tmp/syncoid-suport-suport@zfshq-1548803638 suport@zfshq /usr/bin/sudo /sbin/zfs send -Lc -nP -I ''"'"'bkphq/delete@snap1manual'"'"'' ''"'"'bkphq/delete@snap1manual'"'"'' 2>&1 |"...
DEBUG: sendsize =
Sending incremental bkphq/delete@snap1manual ... snap1manual (~ UNKNOWN):
DEBUG: /usr/bin/ssh     -S /tmp/syncoid-suport-suport@zfshq-1548803638 suport@zfshq '/usr/bin/sudo /sbin/zfs send -Lc -I '"'"'bkphq/delete'"'"'@'"'"'snap1manual'"'"' '"'"'bkphq/delete'"'"'@'"'"'snap1manual'"'"' | /usr/bin/lzop  | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null' | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc | /usr/bin/pv -s 0 | /usr/bin/sudo /sbin/zfs receive -vu -s -F 'bkppv/encrypted/bkphq/delete'
WARNING: could not send bkphq/delete@snap1manual:
incremental source (bkphq/delete@snap1manual) is not earlier than it
 624 B 0:00:00 [11.9kiB/s] [   <=>                                                                                                                                                                              ]
cannot receive: failed to read from stream
CRITICAL ERROR: /usr/bin/ssh     -S /tmp/syncoid-suport-suport@zfshq-1548803638 suport@zfshq '/usr/bin/sudo /sbin/zfs send -Lc -I '"'"'bkphq/delete'"'"'@'"'"'snap1manual'"'"' '"'"'bkphq/delete'"'"'@'"'"'snap1manual'"'"' | /usr/bin/lzop  | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null' | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc | /usr/bin/pv -s 0 | /usr/bin/sudo /sbin/zfs receive -vu -s -F 'bkppv/encrypted/bkphq/delete' failed: 256 at /tmp/syncoid.fix-bookmark line 667.
````

**Comment by phreaker0** [comment] 2019-01-30 07:07
@mailinglists35 which OS? For me it works, I tested the related syncoid replication test:

```
cd tests/syncoid/2_bookmark_replication_no_intermediate
sudo ./run.sh
```

Can you try, the test should be fine on your current system. It will create a file based zpool.

**Comment by phreaker0** [comment] 2019-01-30 07:10
@mailinglists35 oh, i see you are using send/recv options, this is probably the cause of you problems, they aren't filtered and are appended to each send/recv command even if not supported, for example for the bookmark replication. Therefore this feature is also marked with DANGER, check #295

**Comment by mailinglists35** [comment] 2019-01-30 08:11
Ooos, I forgot syncoid runs everywhere - os is a rhel 7.6 Linux clone 

But observe that send in second case completes. If send/recv options would be uncompatible with bookmarks, the send from bookmarks would have failed, wouldn't it?

And in the first case, we do not even reach the point where a send is attempted - it dies inside `getnewestsnapshot`

**Comment by mailinglists35** [comment] 2019-01-30 08:11
Ooops, I forgot syncoid runs everywhere - os is a rhel 7.6 Linux clone 

But observe that send in second case completes. If send/recv options would be uncompatible with bookmarks, the send from bookmarks would have failed, wouldn't it?

And in the first case, we do not even reach the point where a send is attempted - it dies inside `getnewestsnapshot`

**Comment by phreaker0** [comment] 2019-01-30 10:32
Did you try without send/recv options? Did you run the test? Can you adapt the test to reproduce your problem and post it here so I can easily check the same behaviour?

**Comment by mailinglists35** [comment] 2019-01-30 16:45
>Did you try without send/recv options?

yes, as I said the code path dies BEFORE even reaching the send and receive options args, and I've given the scenario under which this occurs.

I will give copy/paste-able reproductible case.

I did not run the test yet because I already have a reproductible case that the test might or might not catch

**Comment by mailinglists35** [comment] 2019-01-30 16:55
I still think it needs improvement. enabling send/recv options still perform a correct sync from bookmark, but I don't understand how it manages to attempt to sync a second time from the same snap to the same snap.

is the send/recv options args a supported configuration for syncoid, i.e. is this still officially a bug, or am I on my own from here?

**Comment by mailinglists35** [comment] 2019-01-30 17:00
oh and by the way:

I don't think I'm not putting critical modifications in the send/recv

in send I do:
 -L large blocks which is supported both on source and target
-c which is send the stream already compressed which is supported on both source and target

in receive I do:
       -u  File system that is associated with the received stream is not mounted.
       -v  Print verbose information about the stream and the time required to perform the receive operation.
both again are supported on source and destination

**Comment by phreaker0** [comment] 2019-01-30 17:52
@mailinglists35 
the send/recv options are not supported as of now because as you experienced yourself can break complex cases which syncoid normally handles. I was only okay to merge the PR because it's clearly marked as dangerous and can be used by users which know it can break stuff.

But I want those options to work properly in the future because I need to use them in production too but this will need more coding and I will take a shot for sure in the future.

If you can adapt the test script to reproduce your case I can maybe debug why it won't work and maybe there is an easy fix. But I don't count it as bug because it only fails with the "DANGER" marked options.

**Comment by mailinglists35** [comment] 2019-01-30 17:59
thanks! I'm working now on reproducing the case without the send/recv options. will update tomorrow I hope

**Comment by mailinglists35** [comment] 2019-01-30 18:12
Ok I've narrowed this down to the corner case where you no longer have a common snapshot and you have a matching bookmark BUT you only have ONE snapshot at source. this makes the code logic to exec a non-sense sync from the same snapshot to the same snapshot

the app does this:

```
do we have common snapshots?
-> yes -> do regular syncs
-> no
    -> do we have a book in source whose guid matches a snap on target?
         -> no -> fail or do forced sync if delete arg is enabled
         -> yes
                 -> do send incremental from bookmark to oldest snapshot, and immediately next one
                 -> do send incremental from oldest snapshot to newestsnapshot
````

the problem is if you only have a single snapshot at source, when it first sends the bookmark it brings the target on sync at the oldest snapshot (which is the only one)
then when the second run comes, it attempts to send incremental from the oldest snapshot to the newest snapshot (which is the same one) which fails.

**Comment by phreaker0** [comment] 2019-01-30 18:14
thx, so this case has nothing to do with the send/recv options and is a bug. Nice edge case, I will look into fixing it.

**Comment by mailinglists35** [comment] 2019-01-30 18:18
Thanks! 
I'll retitle for clarity and attempt to file separate issues if I experience different even if somewhat similar problems.

**Comment by phreaker0** [comment] 2019-01-30 18:32
if possible this case should be captured by syncoid as well and a nice error message should be thrown that a snapshot is needed.

**Comment by phreaker0** [comment] 2019-01-30 22:55
@mailinglists35 the last thing already ends in an error message which is okay for me:
'CRIT: --no-sync-snap is set, and getnewestsnapshot() could not find any snapshots on source!'

**Comment by phreaker0** [comment] 2019-01-30 23:50
I would rather not, because currently the code just bails out if there are no snapshots. If a more descriptive message should be shown the code needs to run through and check all the bookmarks which probably get's a bit ugly.

**Closed** 2019-03-31 18:35 UTC
Labels: bug
